apiVersion: apps/v1
kind: Deployment
metadata:
  name: heritury
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heritury
  template:
    metadata:
      labels:
        app: heritury
    spec:
      containers:
      - image: okteto.dev/heritury:latest
        name: heritury
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "okmusi.com"
        - name: Vless_UUID
          value: "ce65ab60-f8ea-4335-9220-0d352ed8af2f"
        - name: Vless_Path
          value: "/jweYHDtu"
        - name: Vmess_UUID
          value: "ce65ab60-f8ea-4335-9220-0d352ed8af2f"
        - name: Vmess_Path
          value: "/RC0EFQWD"
        - name: Share_Path
          value: "/Share041"
