apiVersion: apps/v1
kind: Deployment
metadata:
  name: rctiony
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rctiony
  template:
    metadata:
      labels:
        app: rctiony
    spec:
      containers:
      - image: okteto.dev/rctiony:latest
        name: rctiony
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mp3-juice.com"
        - name: Vless_UUID
          value: "51f8e92a-479e-4d5a-a2ea-1ba334273135"
        - name: Vless_Path
          value: "/Rdf34uh"
        - name: Vmess_UUID
          value: "51f8e92a-479e-4d5a-a2ea-1ba334273135"
        - name: Vmess_Path
          value: "/scertgf"
        - name: Share_Path
          value: "/Share305"
