apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostiony
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostiony
  template:
    metadata:
      labels:
        app: hostiony
    spec:
      containers:
      - image: okteto.dev/hostiony:latest
        name: hostiony
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.freemusicarchive.org"
        - name: Vless_UUID
          value: "a3888af6-3795-41b4-9b42-4a2ec27bc7a7"
        - name: Vless_Path
          value: "/CIe6rtfy"
        - name: Vmess_UUID
          value: "a3888af6-3795-41b4-9b42-4a2ec27bc7a7"
        - name: Vmess_Path
          value: "/xbr5egt"
        - name: Share_Path
          value: "/Share023"
