apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcertgnb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcertgnb
  template:
    metadata:
      labels:
        app: dcertgnb
    spec:
      containers:
      - image: okteto.dev/dcertgnb:latest
        name: dcertgnb
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.jamendo.com"
        - name: Vless_UUID
          value: "9a259dbb-76e7-4666-913c-ea4ea3d1f65f"
        - name: Vless_Path
          value: "/Tadf3WE"
        - name: Vmess_UUID
          value: "9a259dbb-76e7-4666-913c-ea4ea3d1f65f"
        - name: Vmess_Path
          value: "/gwertf"
        - name: Share_Path
          value: "/Share476"
