apiVersion: apps/v1
kind: Deployment
metadata:
  name: secsatn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secsatn
  template:
    metadata:
      labels:
        app: secsatn
    spec:
      containers:
      - image: okteto.dev/secsatn:latest
        name: secsatn
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "freemp3cloud.com"
        - name: Vless_UUID
          value: "217a238d-ed38-487a-8832-f61adf021584"
        - name: Vless_Path
          value: "/tnbkj4d"
        - name: Vmess_UUID
          value: "217a238d-ed38-487a-8832-f61adf021584"
        - name: Vmess_Path
          value: "/GyhgHJ"
        - name: Share_Path
          value: "/Share241"
